
module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        USER_UPDATE: "USER_UPDATE",
        USER_DELETE: "USER_DELETE",
        USER_STATUS: "USER_STATUS",
        LEAD_ADD_NEW: "LEAD_ADD_NEW",
        CONFIRMATION: "CONFIRMATION",
        ROLES_ADD_NEW: "ROLES_ADD_NEW",
        ROLES_UPDATE: "ROLES_UPDATE",
        OPORATION_TYPE_ADD: "OPORATION_TYPE_ADD",
        OPORATION_TYPE_DELETE: "OPORATION_TYPE_DELETE",
        OPORATION_TYPE_UPDATE: "OPORATION_TYPE_UPDATE",
        OPORATOR_ADD: "OPORATOR_ADD",
        OPORATOR_EDIT: "OPORATOR_EDIT",
        OPORATOR_DELETE: "OPORATOR_DELETE",
        BRANDS_ADD_NEW: "BRANDS_ADD_NEW",
        BRANDS_DELETE: "BRANDS_DELETE",
        BRANDS_UPDATE: "BRANDS_UPDATE",
        DEFAULT: "",
    },

    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
        CALENDAR_EVENTS: "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        LEAD_DELETE: "LEAD_DELETE",
        ROLES_DELETE: "ROLES_DELETE",

    },
});
